# Generated by Django 3.1.6 on 2021-05-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epitope_extraction_tool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatentFile',
        ),
    ]
