# Generated by Django 3.1.6 on 2021-05-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epitope_extraction_tool', '0002_delete_patentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='protein',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
    ]
