# Generated by Django 3.1.6 on 2021-05-09 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epitope_extraction_tool', '0003_auto_20210509_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epitope',
            name='sequence',
        ),
        migrations.AddField(
            model_name='epitope',
            name='epitope',
            field=models.CharField(default='', max_length=512, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
    ]
