version: '3'

services:
    db:
        container_name: db
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/      
        environment:    
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=dev


    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db

volumes:
    postgres_data:
